### ISSUE TITLE
Board page

### ISSUE THREAD

**Issue by fernandovmp** [fernandovmp/kanban-board#6]
Create the board page where the tasks can be managed.

### UI prototype
![Board](https://user-images.githubusercontent.com/45287292/88567994-a552ad80-d00e-11ea-9c99-ca3c42c8f0db.png)

Features:

- [x] Users can see all the task lists on the kanban board.
- [x] User can see all the tasks inside of their list.
- [x] #4 Users can create a new task list on the kanban board.
- [x] #5 Users can create a task inside of a task list.
- [x] #42 Users can change the board title.
- [x] #48 Users can change the list title.
- [x] User can drag and drop a task to another list.
- [x] User can delete the board.
